language: python

dist: xenial

branches:
  only:
    - master
    - develop

python:
  - "2.7"
  - "3.6"

install:
  - pip install coveralls

script:
  - make test

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then coveralls; fi;
